# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006
  syslog/server:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
    operators:
      - type: syslog_parser
        protocol: rfc5424
  syslog/collector:
    tcp:
      listen_address: "0.0.0.0:54527"
    protocol: rfc5424
    operators:
      - type: syslog_parser
        protocol: rfc5424

processors:
  attributes/fluent:
    actions:
      - action: insert
        key: tag
        from_attribute: fluent.tag
      - action: insert
        key: loki.attribute.labels
        value: tag
  attributes/server:
    actions:
      - action: insert
        key: syslog
        value: server_eshop
      - action: insert
        key: loki.attribute.labels
        value: syslog
  attributes/collector:
    actions:
      - action: insert
        key: syslog
        value: syslog_collector
      - action: insert
        key: loki.attribute.labels
        value: syslog

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [attributes/fluent]
      exporters: [loki]
    logs/syslog_server:
      receivers: [syslog/server]
      processors: [attributes/server]
      exporters: [loki]
    logs/syslog_colector:
      receivers: [syslog/collector]
      processors: [attributes/collector]
      exporters: [loki]
