{
 "title": "Syslog",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Count of logs from eshop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({syslog=\"server_eshop\"} != `server systemd-logind[816]` [1h])"
    }
   ]
  },
  {
   "title": "Count of logs from collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({syslog=\"syslog_collector\"} != `server systemd-logind[816]` [1h])"
    }
   ]
  },
  {
   "title": "Syslog eshop",
   "type": "logs",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{syslog=\"server_eshop\"} != `server systemd-logind[816]`"
    }
   ]
  },
  {
   "title": "Syslog collector",
   "type": "logs",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{syslog=\"syslog_collector\"} != `server systemd-logind[816]`"
    }
   ]
  }
 ]
}